global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 20.0
  width: 50.0
  height: 60.0
  resolution: 0.05
  origin_x: -25.0
  origin_y: -30.0
  static_map: true
  rolling_window: false
  always_send_full_costmap: false
