local_costmap:
   global_frame: map 
   robot_base_frame: base_link
   update_frequency: 20.0
   publish_frequency: 20.0
   width: 5.0
   height: 5.0
   resolution: 0.05
   static_map: true
   rolling_window: true
