map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.0
robot_radius: 0.265

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  enabled: true
  observation_sources: scan
  scan: {sensor_frame: map, data_type: LaserScan, topic: front/scan, marking: true, clearing: true, inf_is_valid: true, observation_keep_time: 0.0, expected_update_rate: 0, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 5, raytrace_range: 20}
  footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
  footprint_padding: 0.0
  robot_radius: 0.265
  combination_method: 1

inflation_layer:
  enabled: true
  inflation_radius: 1

static_layer:
  enabled: true
  map_topic: map
  subscribe_to_updates: true
